# Generated by Django 5.1.6 on 2025-03-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_subprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofile',
            name='img',
        ),
    ]
