version: "3.9"

services:
  web:
    build: .
    command: gunicorn videoflix_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:  # ACHTUNG: expose, NICHT ports!
      - "8000"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=meinprojekt_db
      - POSTGRES_USER=meinprojekt_user
      - POSTGRES_PASSWORD=sehr_sicheres_passwort
    restart: always

volumes:
  postgres_data:
