# Generated by Django 5.1.6 on 2025-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('clip', 'Clip')], default='movie', help_text='Bitte auswählen: movie oder clip', max_length=10),
        ),
    ]
