# Generated by Django 5.1.6 on 2025-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('movies', 'Movies'), ('clips', 'Clips')], default='movies', help_text='Bitte auswählen: movies oder clips', max_length=10),
        ),
    ]
