# Generated by Django 5.1.6 on 2025-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('clip', 'Clip')], default='movies', help_text='Bitte auswählen: movies oder clips', max_length=10),
        ),
    ]
