# Generated by Django 5.1.6 on 2025-04-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_video_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
    ]
