# Generated by Django 5.1.6 on 2025-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_video_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Dateigröße in Bytes', null=True),
        ),
    ]
